CREATE TABLE `channels` (
  `userId` VARCHAR(25) NOT NULL PRIMARY KEY,
  `login` VARCHAR(25) NOT NULL,
  `prefix` VARCHAR(25) DEFAULT NULL,
  `added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `conduits` (
  `id` VARCHAR(255) NOT NULL PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `commandStats` (
  `command` VARCHAR(255) NOT NULL PRIMARY KEY,
  `count` INT(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `permissions` (
  `userId` VARCHAR(25) NOT NULL PRIMARY KEY,
  `permission` INT(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `tokens` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY,
  `accessToken` VARCHAR(255) NOT NULL,
  `refreshToken` VARCHAR(255) DEFAULT NULL,
  `expiresAt` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
